name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create release package
        run: |
          cd dist
          zip -r ../zapdesk-${{ steps.get_version.outputs.VERSION }}.zip .
          cd ..

      - name: Generate changelog
        id: changelog
        run: |
          if [ -f "CHANGELOG.md" ]; then
            echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
            cat CHANGELOG.md | head -n 50 >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "CHANGELOG=Release ${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: zapdesk-${{ steps.get_version.outputs.VERSION }}.zip
          body: |
            ## Zapdesk v${{ steps.get_version.outputs.VERSION }}

            ### Installation
            1. Download `zapdesk-${{ steps.get_version.outputs.VERSION }}.zip`
            2. Install using Zendesk CLI:
               ```bash
               zcli apps:create zapdesk-${{ steps.get_version.outputs.VERSION }}.zip
               ```

            ### Build Artifacts
            - Compiled application bundle
            - Zendesk app manifest
            - Localization files

            For deployment instructions, see [DEPLOYMENTS.adoc](docs/DEPLOYMENTS.adoc)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
